import type {
  Profile,
  Route,
  RouteWaypoint,
  RouteSkillRequirement,
  Trip,
  TripParticipant,
  TripEquipmentRequirement,
  ParticipantEquipment,
  MedicalInfo,
  Vehicle,
  TransportAssignment,
  SummitLog,
} from '#/types/database'

export const mockProfiles: Profile[] = [
  {
    id: 'user-1',
    display_name: 'Carlos Montaña',
    avatar_url: 'https://i.pravatar.cc/150?u=user-1',
    role: 'organizer',
    approval_status: 'active',
    phone: '+593 99 123 4567',
    neighborhood: 'La Floresta',
    lat: -0.2053,
    lng: -78.4908,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    display_name: 'Ana Rios',
    avatar_url: 'https://i.pravatar.cc/150?u=user-2',
    role: 'expedition_lead',
    approval_status: 'active',
    phone: '+593 98 987 6543',
    neighborhood: 'González Suárez',
    lat: -0.1984,
    lng: -78.4823,
    created_at: '2025-02-10T14:30:00Z',
  },
  {
    id: 'user-3',
    display_name: 'Luis Peña',
    avatar_url: 'https://i.pravatar.cc/150?u=user-3',
    role: 'participant',
    approval_status: 'active',
    phone: '+593 99 555 8888',
    neighborhood: 'Cumbayá',
    lat: -0.2006,
    lng: -78.4406,
    created_at: '2025-03-05T09:15:00Z',
  },
  {
    id: 'user-4',
    display_name: 'María Torres',
    avatar_url: 'https://i.pravatar.cc/150?u=user-4',
    role: 'participant',
    approval_status: 'active',
    phone: '+593 98 444 2222',
    neighborhood: 'Iñaquito',
    lat: -0.1761,
    lng: -78.4850,
    created_at: '2025-03-20T16:45:00Z',
  },
  {
    id: 'user-5',
    display_name: 'Diego Herrera',
    avatar_url: 'https://i.pravatar.cc/150?u=user-5',
    role: 'participant',
    approval_status: 'active',
    phone: '+593 99 777 3333',
    neighborhood: 'Tumbaco',
    lat: -0.2206,
    lng: -78.4008,
    created_at: '2025-04-01T11:00:00Z',
  },
]

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Cotopaxi - Ruta Normal José Ribas',
    description: 'Ascenso al volcán Cotopaxi (5,897 m), segunda cumbre más alta del Ecuador. Ruta clásica que parte desde el refugio José Ribas a 4,864 m.',
    cover_image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1200&q=80',
    story: 'El volcán Cotopaxi es el ícono del Ecuador y una de las montañas más altas del mundo activas. Con 5.897 msnm, su cumbre nevada ha atraído a montañistas de todo el mundo por más de un siglo.\n\nLa ruta normal parte desde el refugio José Ribas a 4.864 msnm. El ascenso comienza en la medianoche para evitar los fuertes vientos de la tarde y alcanzar la cumbre al amanecer. Los primeros kilómetros atraviesan campo de piedras volcánicas hasta alcanzar el glaciar aproximadamente a 5.000 msnm.\n\nUna vez en el hielo, el uso de crampones y piolet es obligatorio. La pendiente promedio es de 30-35 grados, con algunos tramos que llegan a 40 grados cerca de la cumbre. El cráter del Cotopaxi es impresionante: un ancho de 800 metros y una profundidad de más de 1.000 metros. Desde la cumbre se divisan los volcanes Antisana, Cayambe y Chimborazo en días despejados.',
    difficulty: 'advanced',
    gpx_parsed: { distance: 4, elevation_gain: 1033, elevation_loss: 1033 },
    source_url: 'https://www.wikiloc.com/rutas-alpinismo/cotopaxi-ruta-normal',
    created_by: 'user-1',
    created_at: '2025-01-20T08:00:00Z',
  },
  {
    id: 'route-2',
    name: 'Chimborazo - Ruta Whymper (Cumbre Máxima)',
    description: 'Ascenso al Chimborazo (6,263 m), el punto más alejado del centro de la Tierra. Ruta clásica Whymper desde el refugio Whymper.',
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    story: 'El Chimborazo es una montaña legendaria. Con 6.263 msnm, no es la más alta del mundo, pero gracias al abultamiento ecuatorial de la Tierra, su cumbre es el punto más alejado del centro del planeta, superando incluso al Everest.\n\nLa ruta Whymper, nombrada en honor al primer ascensionista Edward Whymper en 1880, parte desde el refugio Whymper a 5.000 msnm. El ascenso técnico atraviesa glaciar activo con grietas y seracs que exigen navegación cuidadosa.\n\nEl recorrido incluye una parada en el campo alto a 5.600 msnm antes del empuje final hacia las dos cumbres: Veintimilla (6.263 m) y Whymper (6.267 m). La altura extrema y la exposición hacen de este ascenso uno de los más desafiantes de Sudamérica. Solo alrededor del 50% de los intentos logran la cumbre debido a las condiciones meteorológicas impredecibles.',
    difficulty: 'expert',
    gpx_parsed: { distance: 8, elevation_gain: 1300, elevation_loss: 1300 },
    source_url: 'https://www.wikiloc.com/rutas-alpinismo/chimborazo-ruta-whymper',
    created_by: 'user-2',
    created_at: '2025-02-15T10:30:00Z',
  },
  {
    id: 'route-3',
    name: 'Rucu Pichincha - Ruta Normal desde Quito',
    description: 'Ascenso al Rucu Pichincha (4,696 m), volcán activo visible desde Quito. Accesible desde la ciudad, ruta popular para aclimatación.',
    cover_image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80',
    story: 'El Rucu Pichincha es el guardián de Quito. Con 4.696 msnm, esta cumbre volcánica es visible desde casi cualquier punto de la capital ecuatoriana y es una de las rutas de aclimatación más populares del país.\n\nLa ruta normal utiliza el Teleférico de Quito, que parte desde 2.950 msnm y lleva a los caminantes hasta los 3.945 msnm en solo 20 minutos. Desde allí, el sendero asciende por una cresta herbosa con pendientes moderadas.\n\nA mitad de camino se cruza con la ruta hacia el Guagua Pichincha, el hermano gemelo del Rucu. El tramo final incluye una corta sección de trepada en roca (II grado) antes de alcanzar la cumbre. Desde arriba, la vista de Quito a 4.696 metros de altura es simplemente espectacular: una ciudad de 3 millones de habitantes extendida a tus pies, rodeada por la Cordillera de los Andes.',
    difficulty: 'intermediate',
    gpx_parsed: { distance: 8, elevation_gain: 800, elevation_loss: 800 },
    source_url: 'https://www.wikiloc.com/rutas-senderismo/rucu-pichincha',
    created_by: 'user-1',
    created_at: '2025-03-10T07:45:00Z',
  },
  {
    id: 'route-4',
    name: 'Iliniza Norte - Ruta de la Arista',
    description: 'Ascenso al Iliniza Norte (5,126 m), excelente para entrenamiento antes de Cotopaxi o Chimborazo. Ruta técnica por arista.',
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    story: 'El Iliniza Norte es la montaña de entrenamiento por excelencia en Ecuador. Con 5.126 msnm, ofrece la combinación perfecta de altura, técnica y accesibilidad para quienes se preparan para el Cotopaxi o el Chimborazo.\n\nLa ruta de la arista parte desde el refugio Nuevos Horizontes a 4.268 msnm. Los primeros kilómetros atraviesan un campo de piedras volcánicas hasta llegar a "La Cueva", un refugio natural de roca a 4.700 msnm que marca el inicio de la parte técnica.\n\nDesde La Cueva, la ruta sigue una arista rocosa expuesta que exige el uso de manos y pies con cuidado. Hay pasos de trepada de hasta III grado. La arista ofrece exposición hacia ambos lados, con vistas impresionantes del Iliniza Sur (5.248 m) y los valles circundantes. La cumbre es una plataforma rocosa desde donde se divisan el Cotopaxi, el Antisana y el Cayambe en días claros.',
    difficulty: 'advanced',
    gpx_parsed: { distance: 6, elevation_gain: 900, elevation_loss: 900 },
    source_url: 'https://www.wikiloc.com/rutas-alpinismo/iliniza-norte',
    created_by: 'user-2',
    created_at: '2025-04-05T09:00:00Z',
  },
]

export const mockRouteWaypoints: RouteWaypoint[] = [
  { id: 'wp-1', route_id: 'route-1', name: 'Refugio José Ribas', lat: -0.6833, lng: -78.4386, elevation: 4864, order_index: 0, type: 'start' },
  { id: 'wp-2', route_id: 'route-1', name: 'Campamento de piedra', lat: -0.6767, lng: -78.4344, elevation: 5200, order_index: 1, type: 'waypoint' },
  { id: 'wp-3', route_id: 'route-1', name: 'Cumbre Cotopaxi', lat: -0.6838, lng: -78.4382, elevation: 5897, order_index: 2, type: 'summit' },
  { id: 'wp-4', route_id: 'route-1', name: 'Refugio José Ribas', lat: -0.6833, lng: -78.4386, elevation: 4864, order_index: 3, type: 'end' },

  { id: 'wp-5', route_id: 'route-2', name: 'Refugio Whymper', lat: -1.4697, lng: -78.8175, elevation: 5000, order_index: 0, type: 'start' },
  { id: 'wp-6', route_id: 'route-2', name: 'Campo alto', lat: -1.4667, lng: -78.8167, elevation: 5600, order_index: 1, type: 'waypoint' },
  { id: 'wp-7', route_id: 'route-2', name: 'Cumbre Chimborazo (Veintimilla)', lat: -1.4692, lng: -78.8175, elevation: 6263, order_index: 2, type: 'summit' },
  { id: 'wp-8', route_id: 'route-2', name: 'Cumbre Chimborazo (Whymper)', lat: -1.4694, lng: -78.8178, elevation: 6267, order_index: 3, type: 'summit' },
  { id: 'wp-9', route_id: 'route-2', name: 'Refugio Whymper', lat: -1.4697, lng: -78.8175, elevation: 5000, order_index: 4, type: 'end' },

  { id: 'wp-10', route_id: 'route-3', name: 'Estación Teleférico Quito', lat: -0.1876, lng: -78.5085, elevation: 3945, order_index: 0, type: 'start' },
  { id: 'wp-11', route_id: 'route-3', name: 'Cruce de Guagua Pichincha', lat: -0.1756, lng: -78.5981, elevation: 4200, order_index: 1, type: 'waypoint' },
  { id: 'wp-12', route_id: 'route-3', name: 'Cumbre Rucu Pichincha', lat: -0.1869, lng: -78.5708, elevation: 4696, order_index: 2, type: 'summit' },
  { id: 'wp-13', route_id: 'route-3', name: 'Estación Teleférico Quito', lat: -0.1876, lng: -78.5085, elevation: 3945, order_index: 3, type: 'end' },

  { id: 'wp-14', route_id: 'route-4', name: 'Refugio Nuevos Horizontes', lat: -0.6594, lng: -78.7156, elevation: 4268, order_index: 0, type: 'start' },
  { id: 'wp-15', route_id: 'route-4', name: 'La Cueva', lat: -0.6589, lng: -78.7133, elevation: 4700, order_index: 1, type: 'waypoint' },
  { id: 'wp-16', route_id: 'route-4', name: 'Cumbre Iliniza Norte', lat: -0.6606, lng: -78.7142, elevation: 5126, order_index: 2, type: 'summit' },
  { id: 'wp-17', route_id: 'route-4', name: 'Refugio Nuevos Horizontes', lat: -0.6594, lng: -78.7156, elevation: 4268, order_index: 3, type: 'end' },
]

export const mockRouteSkills: RouteSkillRequirement[] = [
  { id: 'skill-1', route_id: 'route-1', skill_tag: 'Uso de crampones' },
  { id: 'skill-2', route_id: 'route-1', skill_tag: 'Manejo de piolet' },
  { id: 'skill-3', route_id: 'route-1', skill_tag: 'Aclimatación a gran altura' },
  { id: 'skill-4', route_id: 'route-1', skill_tag: 'Físico avanzado' },
  { id: 'skill-5', route_id: 'route-2', skill_tag: 'Uso de crampones' },
  { id: 'skill-6', route_id: 'route-2', skill_tag: 'Técnicas de autodetención' },
  { id: 'skill-7', route_id: 'route-2', skill_tag: 'Manejo de piolet' },
  { id: 'skill-8', route_id: 'route-2', skill_tag: 'Aclimatación extrema' },
  { id: 'skill-9', route_id: 'route-2', skill_tag: 'Físico de élite' },
  { id: 'skill-10', route_id: 'route-3', skill_tag: 'Trekking de altura' },
  { id: 'skill-11', route_id: 'route-3', skill_tag: 'Aclimatación moderada' },
  { id: 'skill-12', route_id: 'route-3', skill_tag: 'Físico intermedio' },
  { id: 'skill-13', route_id: 'route-4', skill_tag: 'Trekking técnico' },
  { id: 'skill-14', route_id: 'route-4', skill_tag: 'Uso de manos' },
  { id: 'skill-15', route_id: 'route-4', skill_tag: 'Aclimatación a gran altura' },
  { id: 'skill-16', route_id: 'route-4', skill_tag: 'Físico avanzado' },
]

export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    route_id: 'route-1',
    organizer_id: 'user-1',
    title: 'Ascenso Cotopaxi — Enero 2026',
    meeting_point: 'Estacionamiento Teleférico Quito, Ecuador',
    meeting_lat: -0.1876,
    meeting_lng: -78.5085,
    start_date: '2026-01-15T04:00:00Z',
    end_date: '2026-01-17T20:00:00Z',
    pace: 'medium',
    status: 'open',
    max_participants: 8,
    cover_image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1200&q=80',
    story: 'Una aventura inolvidable al volcán Cotopaxi. Partimos desde Quito a las 4:00 AM con el equipo completo. La primera jornada nos llevó al refugio José Ribas a 4.864 msnm para aclimatación. La noche fue fría pero despejada, con una vía láctea impresionante sobre el cono perfecto del volcán.\n\nEl segundo día iniciamos el ataque a cumbre a la medianoche. Las condiciones de hielo eran perfectas y todos los participantes lograron llegar a la cumbre a las 7:30 AM. El cráter humeante se veía espectacular con la luz del amanecer y el Chimborazo asomaba en el horizonte.',
    created_at: '2025-11-01T10:00:00Z',
  },
  {
    id: 'trip-2',
    route_id: 'route-3',
    organizer_id: 'user-2',
    title: 'Rucu Pichincha Weekend',
    meeting_point: 'Estación Teleférico Quito, Quito',
    meeting_lat: -0.1876,
    meeting_lng: -78.5085,
    start_date: '2025-12-20T06:00:00Z',
    end_date: '2025-12-21T18:00:00Z',
    pace: 'sport',
    status: 'completed',
    max_participants: 12,
    cover_image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80',
    story: 'El Rucu Pichincha nunca decepciona. Esta vez salimos desde el Teleférico de Quito con un grupo de 8 personas. El ascenso fue rápido gracias al buen ritmo del grupo y la aclimatación previa.\n\nEn la cumbre tuvimos una neblina matutina que se disipó justo al mediodía, regalándonos vistas panorámicas de Quito y los valles circundantes. Bajamos por la tarde y celebramos con cervezas artesanales en La Floresta.',
    created_at: '2025-10-15T14:00:00Z',
  },
  {
    id: 'trip-3',
    route_id: 'route-4',
    organizer_id: 'user-1',
    title: 'Iliniza Norte - Entrenamiento de Arista',
    meeting_point: 'El Chaupi, Provincia de Cotopaxi',
    meeting_lat: -0.6719,
    meeting_lng: -78.7286,
    start_date: '2026-02-08T07:00:00Z',
    end_date: '2026-02-08T16:00:00Z',
    pace: 'slow',
    status: 'draft',
    max_participants: 15,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    story: 'Una salida de entrenamiento perfecta para preparar el Cotopaxi. La arista del Iliniza Norte ofrece la combinación ideal de altura y técnica sin llegar al extremo del glaciar.\n\nEl grupo practicó movimientos en roca expuesta y navegación de arista. Desde la cumbre se veía el Cotopaxi completamente despejado, una vista que motivó a todos para la próxima expedición.',
    created_at: '2025-12-01T09:30:00Z',
  },
  {
    id: 'trip-4',
    route_id: 'route-2',
    organizer_id: 'user-2',
    title: 'Chimborazo 5D — Carnavales 2026',
    meeting_point: 'Riobamba, Chimborazo',
    meeting_lat: -1.6716,
    meeting_lng: -78.6479,
    start_date: '2026-02-28T05:00:00Z',
    end_date: '2026-03-04T19:00:00Z',
    pace: 'medium',
    status: 'open',
    max_participants: 6,
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    story: 'El Chimborazo es el sueño de todo andinista ecuatoriano. Esta expedición de 5 días incluye días de aclimatación progresiva en el refugio Whymper y campo alto antes del intento de cumbre.\n\nLos participantes recorrerán los 1.300 metros de desnivel positivo desde el refugio hasta la cumbre máxima, pasando por la cumbre Veintimilla. El objetivo es alcanzar el punto más alejado del centro de la Tierra.',
    created_at: '2025-11-20T11:00:00Z',
  },
  {
    id: 'trip-5',
    route_id: 'route-3',
    organizer_id: 'user-2',
    title: 'Rucu Pichincha al Amanecer',
    meeting_point: 'Teleférico de Quito, Quito',
    meeting_lat: -0.1876,
    meeting_lng: -78.5085,
    start_date: '2025-11-15T05:00:00Z',
    end_date: '2025-11-15T14:00:00Z',
    pace: 'slow',
    status: 'completed',
    max_participants: 10,
    cover_image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80',
    story: 'Salida madrugadora para ver el amanecer desde el Rucu Pichincha. El cielo de Quito se tiñó de dorado y rosa mientras subíamos por la arista. Desde la cumbre, la ciudad amanecía lentamente a nuestros pies.\n\nUna experiencia mágica que demuestra que no hace falta ir muy lejos para encontrar aventura: desde el centro de Quito hasta los 4.696 msnm en menos de 6 horas.',
    created_at: '2025-10-01T09:00:00Z',
  },
]

export const mockTripParticipants: TripParticipant[] = [
  { id: 'tp-1', trip_id: 'trip-1', profile_id: 'user-2', status: 'confirmed', needs_transport: false, registered_at: '2025-11-02T10:00:00Z' },
  { id: 'tp-2', trip_id: 'trip-1', profile_id: 'user-3', status: 'confirmed', needs_transport: true, registered_at: '2025-11-03T14:20:00Z' },
  { id: 'tp-3', trip_id: 'trip-1', profile_id: 'user-4', status: 'pending', needs_transport: true, registered_at: '2025-11-10T09:15:00Z' },
  { id: 'tp-4', trip_id: 'trip-2', profile_id: 'user-1', status: 'confirmed', needs_transport: false, registered_at: '2025-10-16T08:00:00Z' },
  { id: 'tp-5', trip_id: 'trip-2', profile_id: 'user-3', status: 'confirmed', needs_transport: true, registered_at: '2025-10-20T11:30:00Z' },
  { id: 'tp-6', trip_id: 'trip-2', profile_id: 'user-5', status: 'confirmed', needs_transport: true, registered_at: '2025-11-01T16:00:00Z' },
  { id: 'tp-7', trip_id: 'trip-4', profile_id: 'user-1', status: 'confirmed', needs_transport: false, registered_at: '2025-11-25T10:00:00Z' },
  { id: 'tp-8', trip_id: 'trip-4', profile_id: 'user-3', status: 'pending', needs_transport: true, registered_at: '2025-12-05T13:45:00Z' },
]

export const mockTripEquipment: TripEquipmentRequirement[] = [
  { id: 'eq-1', trip_id: 'trip-1', item_name: 'Crampones', mandatory: true },
  { id: 'eq-2', trip_id: 'trip-1', item_name: 'Piolet', mandatory: true },
  { id: 'eq-3', trip_id: 'trip-1', item_name: 'Casco', mandatory: true },
  { id: 'eq-4', trip_id: 'trip-1', item_name: 'Gafas de sol UV400', mandatory: true },
  { id: 'eq-5', trip_id: 'trip-1', item_name: 'Botas de montaña', mandatory: true },
  { id: 'eq-6', trip_id: 'trip-1', item_name: 'Cuerda 60m', mandatory: false },
  { id: 'eq-7', trip_id: 'trip-2', item_name: 'Botas de trekking', mandatory: true },
  { id: 'eq-8', trip_id: 'trip-2', item_name: 'Ropa impermeable', mandatory: true },
  { id: 'eq-9', trip_id: 'trip-2', item_name: 'Cantimplora 2L', mandatory: true },
]

export const mockParticipantEquipment: ParticipantEquipment[] = [
  { id: 'pe-1', participant_id: 'tp-2', equipment_id: 'eq-1', status: 'needs_rental' },
  { id: 'pe-2', participant_id: 'tp-2', equipment_id: 'eq-2', status: 'owned' },
  { id: 'pe-3', participant_id: 'tp-2', equipment_id: 'eq-3', status: 'owned' },
  { id: 'pe-4', participant_id: 'tp-2', equipment_id: 'eq-4', status: 'needs_rental' },
  { id: 'pe-5', participant_id: 'tp-2', equipment_id: 'eq-5', status: 'owned' },
]

export const mockMedicalInfo: MedicalInfo[] = [
  {
    id: 'med-1',
    profile_id: 'user-1',
    blood_type: 'O+',
    allergies: ['Polen', 'Picadura de abeja'],
    medications: 'Ninguna',
    notes: 'Portador de EpiPen',
  },
  {
    id: 'med-2',
    profile_id: 'user-2',
    blood_type: 'A-',
    allergies: [],
    medications: 'Ninguna',
    notes: '',
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    owner_id: 'user-1',
    trip_id: 'trip-1',
    model: 'Toyota Land Cruiser Prado',
    capacity: 4,
    tags: ['4x4', 'Baúl amplio', 'Aire acondicionado'],
    is_confirmed: true,
  },
  {
    id: 'veh-2',
    owner_id: 'user-2',
    trip_id: 'trip-1',
    model: 'Mitsubishi Montero Sport',
    capacity: 3,
    tags: ['4x4', 'Tracción doble'],
    is_confirmed: true,
  },
]

export const mockTransportAssignments: TransportAssignment[] = [
  { id: 'ta-1', vehicle_id: 'veh-1', participant_id: 'tp-2', assigned_by: 'user-1' },
  { id: 'ta-2', vehicle_id: 'veh-2', participant_id: 'tp-3', assigned_by: 'user-1' },
]

export const mockSummitLogs: SummitLog[] = [
  {
    id: 'sl-1',
    profile_id: 'user-1',
    trip_id: 'trip-1',
    route_id: 'route-1',
    completed_at: '2026-01-16T11:30:00Z',
    notes: 'Condiciones perfectas. Sin viento en cumbre. Vista del Chimborazo.',
  },
  {
    id: 'sl-2',
    profile_id: 'user-2',
    trip_id: 'trip-2',
    route_id: 'route-3',
    completed_at: '2025-12-20T13:00:00Z',
    notes: 'Neblina en la mañana pero se despejó al mediodía. Vista de Quito espectacular.',
  },
]
