import type {
  Profile,
  Route,
  RouteWaypoint,
  RouteSkillRequirement,
  Trip,
  TripParticipant,
  TripEquipmentRequirement,
  ParticipantEquipment,
  MedicalInfo,
  Vehicle,
  TransportAssignment,
  SummitLog,
} from '#/types/database'

export const mockProfiles: Profile[] = [
  {
    id: 'user-1',
    display_name: 'Carlos Montaña',
    avatar_url: 'https://i.pravatar.cc/150?u=user-1',
    role: 'organizer',
    phone: '+57 300 123 4567',
    neighborhood: 'Chapinero',
    lat: 4.6483,
    lng: -74.0628,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    display_name: 'Ana Rios',
    avatar_url: 'https://i.pravatar.cc/150?u=user-2',
    role: 'guide',
    phone: '+57 310 987 6543',
    neighborhood: 'Usaquén',
    lat: 4.7021,
    lng: -74.0308,
    created_at: '2025-02-10T14:30:00Z',
  },
  {
    id: 'user-3',
    display_name: 'Luis Peña',
    avatar_url: 'https://i.pravatar.cc/150?u=user-3',
    role: 'participant',
    phone: '+57 320 555 8888',
    neighborhood: 'Suba',
    lat: 4.7436,
    lng: -74.0827,
    created_at: '2025-03-05T09:15:00Z',
  },
  {
    id: 'user-4',
    display_name: 'María Torres',
    avatar_url: 'https://i.pravatar.cc/150?u=user-4',
    role: 'participant',
    phone: '+57 315 444 2222',
    neighborhood: 'Teusaquillo',
    lat: 4.6243,
    lng: -74.0892,
    created_at: '2025-03-20T16:45:00Z',
  },
  {
    id: 'user-5',
    display_name: 'Diego Herrera',
    avatar_url: 'https://i.pravatar.cc/150?u=user-5',
    role: 'participant',
    phone: '+57 317 777 3333',
    neighborhood: 'Envigado',
    lat: 6.1676,
    lng: -75.5838,
    created_at: '2025-04-01T11:00:00Z',
  },
]

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Cumbre del Nevado del Tolima',
    description: 'Ascenso técnico al Nevado del Tolima por la ruta tradicional. Requiere experiencia en hielo y nieve.',
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    story: 'El Nevado del Tolima es uno de los picos más icónicos de la Cordillera Central. Con 5.216 msnm, su cumbre nevada ha sido el objetivo de montañistas colombianos por décadas.\n\nLa ruta tradicional parte desde la Finca El Silencio en el departamento del Tolima. El primer día consiste en una caminata de aproximadamente 8 km hasta el campamento base a 4.100 msnm. El segundo día es el ataque a cumbre: se sale a las 2:00 AM para evitar los fuertes vientos de la tarde y alcanzar la cumbre al amanecer.\n\nEl recorrido incluye pasos por glaciar activo, por lo que es obligatorio el uso de crampones y piolet. La exposición en algunos tramos es considerable y se requiere manejo básico de cuerdas para los pasos más técnicos.',
    difficulty: 'expert',
    gpx_parsed: { distance: 28.5, elevation_gain: 2200, elevation_loss: 2200 },
    source_url: 'https://wikiloc.com/rutas-senderismo/nevado-del-tolima',
    created_by: 'user-1',
    created_at: '2025-01-20T08:00:00Z',
  },
  {
    id: 'route-2',
    name: 'Laguna de Iguaque',
    description: 'Caminata cultural y ecológica por la laguna sagrada de Iguaque en el Parque Nacional de Iguaque.',
    cover_image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80',
    story: 'La laguna de Iguaque es considerada el ombligo del mundo en la mitología Muisca. Ubicada a 3.680 msnm en el Parque Nacional de Iguaque, esta ruta combina naturaleza, historia y espiritualidad.\n\nEl recorrido inicia en la entrada del parque y asciende gradualmente por un sendero bien marcado que atraviesa bosques de frailejón y páramo. A mitad de camino se encuentra la laguna Chiquita, un excelente punto para descansar antes del tramo final.\n\nLa llegada a la laguna de Iguaque ofrece un paisaje sobrecogedor: aguas cristalinas rodeadas de frailejones y montañas. Es una ruta accesible para principiantes en buena condición física.',
    difficulty: 'beginner',
    gpx_parsed: { distance: 14.2, elevation_gain: 800, elevation_loss: 800 },
    source_url: 'https://wikiloc.com/rutas-senderismo/laguna-de-iguaque',
    created_by: 'user-2',
    created_at: '2025-02-15T10:30:00Z',
  },
  {
    id: 'route-3',
    name: 'Pico de Loro',
    description: 'Clásica ruta del Pico de Loro en el Parque Nacional Natural Farallones de Cali. Vistas espectaculares del Valle del Cauca.',
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    story: 'El Pico de Loro, con 2.860 msnm, es uno de los cerros tutelares de Cali y una de las rutas más populares del suroccidente colombiano. Su nombre proviene de la forma del pico, que recuerda al pico de un loro.\n\nLa ruta inicia desde el sector de Peñas Blancas en el Pance. El sendero es exigente desde el inicio, con pendientes pronunciadas que demandan buena condición física. A medida que se asciende, el bosque húmedo tropical da paso a bosque de niebla.\n\nLa cumbre ofrece una vista panorámica 360 grados del Valle del Cauca: de un lado se ve Cali y Yumbo, del otro los Farallones y la Cordillera Occidental. Es una ruta de un solo día, ideal para quienes buscan un reto moderado con gran recompensa visual.',
    difficulty: 'intermediate',
    gpx_parsed: { distance: 18.0, elevation_gain: 1400, elevation_loss: 1400 },
    source_url: 'https://wikiloc.com/rutas-senderismo/pico-de-loro',
    created_by: 'user-1',
    created_at: '2025-03-10T07:45:00Z',
  },
  {
    id: 'route-4',
    name: 'Cocuy Circuito Clásico',
    description: 'Circuito de 5 días por el Parque Nacional Natural El Cocuy. Incluye ascensos a Ritacuba Blanco y Pan de Azúcar.',
    cover_image: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&q=80',
    story: 'El Parque Nacional Natural El Cocuy alberga el sistema glaciar más grande de Colombia después del Nevado de Santa Isabel. El circuito clásico es una travesía de 5 días que recorre los valles de Lagunillas, Cóncavo y la Sierra Nevada del Cocuy.\n\nEl primer día lleva desde la cabaña de Kanwara hasta el valle de Lagunillas. El segundo día asciende a Ritacuba Blanco (5.410 msnm), el pico más alto del parque. Los días siguientes incluyen el paso por el Paso de Bellavista, la laguna Grande de la Sierra y el Pan de Azúcar.\n\nEs una expedición que demanda excelente condición física, aclimatación previa y experiencia en acampada de altura. Los paisajes de páramo, glaciares y lagunas de color esmeralda hacen de este uno de los trekings más impresionantes de Sudamérica.',
    difficulty: 'advanced',
    gpx_parsed: { distance: 52.0, elevation_gain: 3500, elevation_loss: 3500 },
    source_url: 'https://wikiloc.com/rutas-senderismo/cocuy-circuito',
    created_by: 'user-2',
    created_at: '2025-04-05T09:00:00Z',
  },
]

export const mockRouteWaypoints: RouteWaypoint[] = [
  { id: 'wp-1', route_id: 'route-1', name: 'Finca El Silencio', lat: 4.6583, lng: -75.3228, elevation: 3200, order_index: 0, type: 'start' },
  { id: 'wp-2', route_id: 'route-1', name: 'Campamento Base', lat: 4.6601, lng: -75.3154, elevation: 4100, order_index: 1, type: 'waypoint' },
  { id: 'wp-3', route_id: 'route-1', name: 'Cumbre Nevado del Tolima', lat: 4.6742, lng: -75.3247, elevation: 5215, order_index: 2, type: 'summit' },
  { id: 'wp-4', route_id: 'route-1', name: 'Retorno Finca', lat: 4.6583, lng: -75.3228, elevation: 3200, order_index: 3, type: 'end' },

  { id: 'wp-5', route_id: 'route-2', name: 'Entrada Parque', lat: 5.4167, lng: -73.4500, elevation: 2800, order_index: 0, type: 'start' },
  { id: 'wp-6', route_id: 'route-2', name: 'Laguna de Iguaque', lat: 5.4234, lng: -73.4456, elevation: 3680, order_index: 1, type: 'summit' },
  { id: 'wp-7', route_id: 'route-2', name: 'Salida', lat: 5.4167, lng: -73.4500, elevation: 2800, order_index: 2, type: 'end' },

  { id: 'wp-8', route_id: 'route-3', name: 'Base Farallones', lat: 3.4167, lng: -76.5333, elevation: 1800, order_index: 0, type: 'start' },
  { id: 'wp-9', route_id: 'route-3', name: 'Pico de Loro', lat: 3.4256, lng: -76.5289, elevation: 2860, order_index: 1, type: 'summit' },
  { id: 'wp-10', route_id: 'route-3', name: 'Retorno', lat: 3.4167, lng: -76.5333, elevation: 1800, order_index: 2, type: 'end' },
]

export const mockRouteSkills: RouteSkillRequirement[] = [
  { id: 'skill-1', route_id: 'route-1', skill_tag: 'Manejo de cuerdas' },
  { id: 'skill-2', route_id: 'route-1', skill_tag: 'Autodetención en hielo' },
  { id: 'skill-3', route_id: 'route-1', skill_tag: 'Uso de crampones' },
  { id: 'skill-4', route_id: 'route-1', skill_tag: 'Nivel físico avanzado' },
  { id: 'skill-5', route_id: 'route-4', skill_tag: 'Manejo de cuerdas' },
  { id: 'skill-6', route_id: 'route-4', skill_tag: 'Acampada de altura' },
  { id: 'skill-7', route_id: 'route-4', skill_tag: 'Nivel físico avanzado' },
  { id: 'skill-8', route_id: 'route-3', skill_tag: 'Nivel físico intermedio' },
]

export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    route_id: 'route-1',
    organizer_id: 'user-1',
    title: 'Ascenso Tolima — Enero 2026',
    meeting_point: 'Parqueadero Terminal Salitre, Bogotá',
    meeting_lat: 4.6473,
    meeting_lng: -74.0955,
    start_date: '2026-01-15T04:00:00Z',
    end_date: '2026-01-17T20:00:00Z',
    pace: 'medium',
    status: 'open',
    max_participants: 8,
    cover_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    story: 'Una aventura inolvidable al Nevado del Tolima. Partimos desde Ibagué a las 4:00 AM con el equipo completo. La primera jornada nos llevó a establecer el campamento base a 4,100 msnm. La noche fue fría pero despejada, con una vía láctea impresionante.\n\nEl segundo día iniciamos el ataque a cumbre a las 2:00 AM. Las condiciones de hielo eran perfectas y todos los participantes lograron llegar a la cumbre a las 7:30 AM. El glaciar se veía espectacular con la luz del amanecer.',
    created_at: '2025-11-01T10:00:00Z',
  },
  {
    id: 'trip-2',
    route_id: 'route-3',
    organizer_id: 'user-2',
    title: 'Pico de Loro Weekend',
    meeting_point: 'Calle 5 # 10-20, Cali',
    meeting_lat: 3.4516,
    meeting_lng: -76.5319,
    start_date: '2025-12-20T06:00:00Z',
    end_date: '2025-12-21T18:00:00Z',
    pace: 'sport',
    status: 'completed',
    max_participants: 12,
    cover_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    story: 'El Pico de Loro nunca decepciona. Esta vez salimos desde Cali con un grupo de 8 personas. El ascenso fue rápido gracias al buen ritmo del grupo.\n\nEn la cumbre tuvimos una neblina matutina que se disipó justo al mediodía, regalándonos vistas panorámicas del Valle del Cauca. Bajamos por la tarde y celebramos con cervezas artesanales en Pance.',
    created_at: '2025-10-15T14:00:00Z',
  },
  {
    id: 'trip-3',
    route_id: 'route-2',
    organizer_id: 'user-1',
    title: 'Iguaque Cultural Walk',
    meeting_point: 'Plaza de Bolívar, Villa de Leyva',
    meeting_lat: 5.6333,
    meeting_lng: -73.5333,
    start_date: '2026-02-08T07:00:00Z',
    end_date: '2026-02-08T16:00:00Z',
    pace: 'slow',
    status: 'draft',
    max_participants: 15,
    cover_image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80',
    story: 'Una caminata suave y cultural por los caminos de la laguna sagrada de Iguaque. Aprendimos sobre la mitología Muisca y la importancia ecológica de este ecosistema de páramo.',
    created_at: '2025-12-01T09:30:00Z',
  },
  {
    id: 'trip-4',
    route_id: 'route-4',
    organizer_id: 'user-2',
    title: 'Cocuy 5D — Carnavales 2026',
    meeting_point: 'Aeropuerto El Dorado, Bogotá',
    meeting_lat: 4.7014,
    meeting_lng: -74.1469,
    start_date: '2026-02-28T05:00:00Z',
    end_date: '2026-03-04T19:00:00Z',
    pace: 'medium',
    status: 'open',
    max_participants: 6,
    cover_image: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&q=80',
    story: 'El circuito clásico del Cocuy es una experiencia de 5 días que todo montañista colombiano debe vivir. Incluye ascensos a Ritacuba Blanco y Pan de Azúcar.',
    created_at: '2025-11-20T11:00:00Z',
  },
  {
    id: 'trip-5',
    route_id: 'route-2',
    organizer_id: 'user-2',
    title: 'Iguaque al Amanecer',
    meeting_point: 'Villa de Leyva, Boyacá',
    meeting_lat: 5.6333,
    meeting_lng: -73.5333,
    start_date: '2025-11-15T05:00:00Z',
    end_date: '2025-11-15T14:00:00Z',
    pace: 'slow',
    status: 'completed',
    max_participants: 10,
    cover_image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80',
    story: 'Salida madrugadora para ver el amanecer desde la laguna de Iguaque. El paramo se tiñó de dorado y rosa mientras subíamos. Una experiencia mágica que recomendamos a todos.',
    created_at: '2025-10-01T09:00:00Z',
  },
]

export const mockTripParticipants: TripParticipant[] = [
  { id: 'tp-1', trip_id: 'trip-1', profile_id: 'user-2', status: 'confirmed', needs_transport: false, registered_at: '2025-11-02T10:00:00Z' },
  { id: 'tp-2', trip_id: 'trip-1', profile_id: 'user-3', status: 'confirmed', needs_transport: true, registered_at: '2025-11-03T14:20:00Z' },
  { id: 'tp-3', trip_id: 'trip-1', profile_id: 'user-4', status: 'pending', needs_transport: true, registered_at: '2025-11-10T09:15:00Z' },
  { id: 'tp-4', trip_id: 'trip-2', profile_id: 'user-1', status: 'confirmed', needs_transport: false, registered_at: '2025-10-16T08:00:00Z' },
  { id: 'tp-5', trip_id: 'trip-2', profile_id: 'user-3', status: 'confirmed', needs_transport: true, registered_at: '2025-10-20T11:30:00Z' },
  { id: 'tp-6', trip_id: 'trip-2', profile_id: 'user-5', status: 'confirmed', needs_transport: true, registered_at: '2025-11-01T16:00:00Z' },
  { id: 'tp-7', trip_id: 'trip-4', profile_id: 'user-1', status: 'confirmed', needs_transport: false, registered_at: '2025-11-25T10:00:00Z' },
  { id: 'tp-8', trip_id: 'trip-4', profile_id: 'user-3', status: 'pending', needs_transport: true, registered_at: '2025-12-05T13:45:00Z' },
]

export const mockTripEquipment: TripEquipmentRequirement[] = [
  { id: 'eq-1', trip_id: 'trip-1', item_name: 'Crampones', mandatory: true },
  { id: 'eq-2', trip_id: 'trip-1', item_name: 'Piolet', mandatory: true },
  { id: 'eq-3', trip_id: 'trip-1', item_name: 'Casco', mandatory: true },
  { id: 'eq-4', trip_id: 'trip-1', item_name: 'Gafas de sol UV400', mandatory: true },
  { id: 'eq-5', trip_id: 'trip-1', item_name: 'Botas de montaña', mandatory: true },
  { id: 'eq-6', trip_id: 'trip-1', item_name: 'Cuerda 60m', mandatory: false },
  { id: 'eq-7', trip_id: 'trip-2', item_name: 'Botas de trekking', mandatory: true },
  { id: 'eq-8', trip_id: 'trip-2', item_name: 'Ropa impermeable', mandatory: true },
  { id: 'eq-9', trip_id: 'trip-2', item_name: 'Cantimplora 2L', mandatory: true },
]

export const mockParticipantEquipment: ParticipantEquipment[] = [
  { id: 'pe-1', participant_id: 'tp-2', equipment_id: 'eq-1', status: 'needs_rental' },
  { id: 'pe-2', participant_id: 'tp-2', equipment_id: 'eq-2', status: 'owned' },
  { id: 'pe-3', participant_id: 'tp-2', equipment_id: 'eq-3', status: 'owned' },
  { id: 'pe-4', participant_id: 'tp-2', equipment_id: 'eq-4', status: 'needs_rental' },
  { id: 'pe-5', participant_id: 'tp-2', equipment_id: 'eq-5', status: 'owned' },
]

export const mockMedicalInfo: MedicalInfo[] = [
  {
    id: 'med-1',
    profile_id: 'user-1',
    blood_type: 'O+',
    allergies: ['Polen', 'Picadura de abeja'],
    medications: 'Ninguna',
    notes: 'Portador de EpiPen',
  },
  {
    id: 'med-2',
    profile_id: 'user-2',
    blood_type: 'A-',
    allergies: [],
    medications: 'Ninguna',
    notes: '',
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    owner_id: 'user-1',
    trip_id: 'trip-1',
    model: 'Toyota Land Cruiser Prado',
    capacity: 4,
    tags: ['4x4', 'Baúl amplio', 'Aire acondicionado'],
    is_confirmed: true,
  },
  {
    id: 'veh-2',
    owner_id: 'user-2',
    trip_id: 'trip-1',
    model: 'Mitsubishi Montero Sport',
    capacity: 3,
    tags: ['4x4', 'Tracción doble'],
    is_confirmed: true,
  },
]

export const mockTransportAssignments: TransportAssignment[] = [
  { id: 'ta-1', vehicle_id: 'veh-1', participant_id: 'tp-2', assigned_by: 'user-1' },
  { id: 'ta-2', vehicle_id: 'veh-2', participant_id: 'tp-3', assigned_by: 'user-1' },
]

export const mockSummitLogs: SummitLog[] = [
  {
    id: 'sl-1',
    profile_id: 'user-1',
    trip_id: 'trip-1',
    route_id: 'route-1',
    completed_at: '2026-01-16T11:30:00Z',
    notes: 'Condiciones perfectas. Sin viento en cumbre.',
  },
  {
    id: 'sl-2',
    profile_id: 'user-2',
    trip_id: 'trip-2',
    route_id: 'route-3',
    completed_at: '2025-12-20T13:00:00Z',
    notes: 'Neblina en la mañana pero se despejó al mediodía.',
  },
]
