/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteGuidesRouteIdRouteImport } from './routes/route-guides.$routeId'
import { Route as ExpeditionsTripIdRouteImport } from './routes/expeditions.$tripId'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppSummitsRouteImport } from './routes/_app.summits'
import { Route as AppRoutesRouteImport } from './routes/_app.routes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsTripIdRouteImport } from './routes/_app.trips.$tripId'
import { Route as AppRoutesNewRouteImport } from './routes/_app.routes.new'
import { Route as AppRoutesRouteIdRouteImport } from './routes/_app.routes.$routeId'
import { Route as AppTripsTripIdTransportRouteImport } from './routes/_app.trips.$tripId.transport'
import { Route as AppTripsTripIdRegisterRouteImport } from './routes/_app.trips.$tripId.register'
import { Route as AppTripsTripIdEditRouteImport } from './routes/_app.trips.$tripId.edit'
import { Route as AppRoutesRouteIdEditRouteImport } from './routes/_app.routes.$routeId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteGuidesRouteIdRoute = RouteGuidesRouteIdRouteImport.update({
  id: '/route-guides/$routeId',
  path: '/route-guides/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsTripIdRoute = ExpeditionsTripIdRouteImport.update({
  id: '/expeditions/$tripId',
  path: '/expeditions/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSummitsRoute = AppSummitsRouteImport.update({
  id: '/summits',
  path: '/summits',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppRoutesNewRoute = AppRoutesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppRoutesRouteIdRoute = AppRoutesRouteIdRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => AppRoutesRoute,
} as any)
const AppTripsTripIdTransportRoute = AppTripsTripIdTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdRegisterRoute = AppTripsTripIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdEditRoute = AppTripsTripIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppRoutesRouteIdEditRoute = AppRoutesRouteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRoutesRouteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/routes': typeof AppRoutesRouteWithChildren
  '/summits': typeof AppSummitsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/expeditions/$tripId': typeof ExpeditionsTripIdRoute
  '/route-guides/$routeId': typeof RouteGuidesRouteIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRouteWithChildren
  '/routes/new': typeof AppRoutesNewRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/routes/$routeId/edit': typeof AppRoutesRouteIdEditRoute
  '/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/trips/$tripId/register': typeof AppTripsTripIdRegisterRoute
  '/trips/$tripId/transport': typeof AppTripsTripIdTransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/routes': typeof AppRoutesRouteWithChildren
  '/summits': typeof AppSummitsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/expeditions/$tripId': typeof ExpeditionsTripIdRoute
  '/route-guides/$routeId': typeof RouteGuidesRouteIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRouteWithChildren
  '/routes/new': typeof AppRoutesNewRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/routes/$routeId/edit': typeof AppRoutesRouteIdEditRoute
  '/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/trips/$tripId/register': typeof AppTripsTripIdRegisterRoute
  '/trips/$tripId/transport': typeof AppTripsTripIdTransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/routes': typeof AppRoutesRouteWithChildren
  '/_app/summits': typeof AppSummitsRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/expeditions/$tripId': typeof ExpeditionsTripIdRoute
  '/route-guides/$routeId': typeof RouteGuidesRouteIdRoute
  '/_app/routes/$routeId': typeof AppRoutesRouteIdRouteWithChildren
  '/_app/routes/new': typeof AppRoutesNewRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/_app/trips/new': typeof AppTripsNewRoute
  '/_app/routes/$routeId/edit': typeof AppRoutesRouteIdEditRoute
  '/_app/trips/$tripId/edit': typeof AppTripsTripIdEditRoute
  '/_app/trips/$tripId/register': typeof AppTripsTripIdRegisterRoute
  '/_app/trips/$tripId/transport': typeof AppTripsTripIdTransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/routes'
    | '/summits'
    | '/trips'
    | '/expeditions/$tripId'
    | '/route-guides/$routeId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/routes/$routeId/edit'
    | '/trips/$tripId/edit'
    | '/trips/$tripId/register'
    | '/trips/$tripId/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/routes'
    | '/summits'
    | '/trips'
    | '/expeditions/$tripId'
    | '/route-guides/$routeId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/routes/$routeId/edit'
    | '/trips/$tripId/edit'
    | '/trips/$tripId/register'
    | '/trips/$tripId/transport'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/routes'
    | '/_app/summits'
    | '/_app/trips'
    | '/expeditions/$tripId'
    | '/route-guides/$routeId'
    | '/_app/routes/$routeId'
    | '/_app/routes/new'
    | '/_app/trips/$tripId'
    | '/_app/trips/new'
    | '/_app/routes/$routeId/edit'
    | '/_app/trips/$tripId/edit'
    | '/_app/trips/$tripId/register'
    | '/_app/trips/$tripId/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ExpeditionsTripIdRoute: typeof ExpeditionsTripIdRoute
  RouteGuidesRouteIdRoute: typeof RouteGuidesRouteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-guides/$routeId': {
      id: '/route-guides/$routeId'
      path: '/route-guides/$routeId'
      fullPath: '/route-guides/$routeId'
      preLoaderRoute: typeof RouteGuidesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions/$tripId': {
      id: '/expeditions/$tripId'
      path: '/expeditions/$tripId'
      fullPath: '/expeditions/$tripId'
      preLoaderRoute: typeof ExpeditionsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summits': {
      id: '/_app/summits'
      path: '/summits'
      fullPath: '/summits'
      preLoaderRoute: typeof AppSummitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/routes/new': {
      id: '/_app/routes/new'
      path: '/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof AppRoutesNewRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/routes/$routeId': {
      id: '/_app/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AppRoutesRouteIdRouteImport
      parentRoute: typeof AppRoutesRoute
    }
    '/_app/trips/$tripId/transport': {
      id: '/_app/trips/$tripId/transport'
      path: '/transport'
      fullPath: '/trips/$tripId/transport'
      preLoaderRoute: typeof AppTripsTripIdTransportRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/register': {
      id: '/_app/trips/$tripId/register'
      path: '/register'
      fullPath: '/trips/$tripId/register'
      preLoaderRoute: typeof AppTripsTripIdRegisterRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/edit': {
      id: '/_app/trips/$tripId/edit'
      path: '/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof AppTripsTripIdEditRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/routes/$routeId/edit': {
      id: '/_app/routes/$routeId/edit'
      path: '/edit'
      fullPath: '/routes/$routeId/edit'
      preLoaderRoute: typeof AppRoutesRouteIdEditRouteImport
      parentRoute: typeof AppRoutesRouteIdRoute
    }
  }
}

interface AppRoutesRouteIdRouteChildren {
  AppRoutesRouteIdEditRoute: typeof AppRoutesRouteIdEditRoute
}

const AppRoutesRouteIdRouteChildren: AppRoutesRouteIdRouteChildren = {
  AppRoutesRouteIdEditRoute: AppRoutesRouteIdEditRoute,
}

const AppRoutesRouteIdRouteWithChildren =
  AppRoutesRouteIdRoute._addFileChildren(AppRoutesRouteIdRouteChildren)

interface AppRoutesRouteChildren {
  AppRoutesRouteIdRoute: typeof AppRoutesRouteIdRouteWithChildren
  AppRoutesNewRoute: typeof AppRoutesNewRoute
}

const AppRoutesRouteChildren: AppRoutesRouteChildren = {
  AppRoutesRouteIdRoute: AppRoutesRouteIdRouteWithChildren,
  AppRoutesNewRoute: AppRoutesNewRoute,
}

const AppRoutesRouteWithChildren = AppRoutesRoute._addFileChildren(
  AppRoutesRouteChildren,
)

interface AppTripsTripIdRouteChildren {
  AppTripsTripIdEditRoute: typeof AppTripsTripIdEditRoute
  AppTripsTripIdRegisterRoute: typeof AppTripsTripIdRegisterRoute
  AppTripsTripIdTransportRoute: typeof AppTripsTripIdTransportRoute
}

const AppTripsTripIdRouteChildren: AppTripsTripIdRouteChildren = {
  AppTripsTripIdEditRoute: AppTripsTripIdEditRoute,
  AppTripsTripIdRegisterRoute: AppTripsTripIdRegisterRoute,
  AppTripsTripIdTransportRoute: AppTripsTripIdTransportRoute,
}

const AppTripsTripIdRouteWithChildren = AppTripsTripIdRoute._addFileChildren(
  AppTripsTripIdRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsTripIdRoute: typeof AppTripsTripIdRouteWithChildren
  AppTripsNewRoute: typeof AppTripsNewRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsTripIdRoute: AppTripsTripIdRouteWithChildren,
  AppTripsNewRoute: AppTripsNewRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRoutesRoute: typeof AppRoutesRouteWithChildren
  AppSummitsRoute: typeof AppSummitsRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppRoutesRoute: AppRoutesRouteWithChildren,
  AppSummitsRoute: AppSummitsRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ExpeditionsTripIdRoute: ExpeditionsTripIdRoute,
  RouteGuidesRouteIdRoute: RouteGuidesRouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
